### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by githubXin123** [wzxxxx/Prompt-MolOpt#1]
Hello! Your work is excellent. However, I can't find the train_linux_prompt.py mentioned in Prompt_molopt_train.sh.
@wzxxxx

**Comment by wzxxxx** [comment]
> Hello! Your work is excellent. However, I can't find the train_linux_prompt.py mentioned in Prompt_molopt_train.sh. @wzxxxx

Thanks for your question, I add the train_linux_prompt.py file.
